name: Contexts
on: push
jobs: 
    print:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ github.run_id}}"
            - run: echo "${{ github.event_name}}"
            - run: echo "${{ github.actor}}"
