name: Manual
on: 
  workflow_dispatch:
    input:
      greeting:
        type: string
        description: 'A cheerful word'
        required: true
        description: 'A cheerful word'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"