name: Manual
on: 
workflow_dispatch
  input:
    greeting:
      type: string
      description: 'Hello, who?'
      required: true
      description: 'Hello'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"