name: Secrets Variables
on: push
jobs:
    run:
        runs-on: ubuntu-latest
        env:
            PASSWORD: ${{ secrets.PASSWORD }}
        steps:
            - run: echo "${PASSWORD}"
            - run: echo "${PASSWORD:0:3} ${PASSWORD#?}"